project_id: 401640
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true

files:
  - source: /docs/*.md
    translation: /docs/%locale_with_underscore%/%original_file_name%
  - source: /docs/.vuepress/i18n/i18n/en_US.js
    translation: /docs/.vuepress/i18n/i18n/%locale_with_underscore%.js
  - source: /docs/.vuepress/i18n/themeConfig/en_US.js
    translation: /docs/.vuepress/i18n/themeConfig/%locale_with_underscore%.js
  - source: /docs/.vuepress/public/assets/images/sdroot/en_US.png
    translation: /docs/.vuepress/public/assets/images/sdroot/%locale_with_underscore%.png
